# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/renvm-demo/ethereum-contracts

commands:
  install_deps:
    description: "Install dependencies"
    steps:
      # Download and cache dependencies
      - restore_cache:
          name: Restore node_modules
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --network-concurrency 1
      - save_cache:
          name: Save node_modules
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

jobs:
  build:
    executor: default
    steps:
      - checkout:
          path: ~/renvm-demo
      - install_deps
      - run:
          name: Run tests
          command: yarn run coverage # && yarn run coveralls

workflows:
  build:
    jobs:
      - build
